apps/urts/urls.py
from django.contrib import admin
from django.urls import path
from apps.urts.views import (urts, urt_ficha, 
                             especie_vegetal_salvar, especie_vegetal_modal, especie_vegetal_deletar,
                             especie_animal_salvar, especie_animal_modal, especie_animal_deletar,
                             tecnico_salvar, tecnico_modal, tecnico_deletar,
                             urt_relatorio_ficha, listagem_ciclos_urt, ciclo_urt_ficha
                             )


urlpatterns = [
    
    #URTs
    path('urts/', urts, name='urts'),

    #FICHA DA URT
    path('urts/ficha/<int:urt_id>/', urt_ficha, name='urt_ficha'),
    path('urts/ficha/salvar/<int:urt_id>/', urt_ficha, name='urt_ficha'),

    #ESPÉCIE VEGETAL
    path('urts/ficha/especie-vegetal/<int:vegetal_id>/dados/', especie_vegetal_modal, name='especie_vegetal_modal'),
    path('urts/ficha/especie-vegetal/salvar/novo/', especie_vegetal_salvar, name='especie_vegetal_salvar_novo'),
    path('urts/ficha/especie-vegetal/salvar/<int:vegetal_id>/', especie_vegetal_salvar, name='especie_vegetal_salvar'),
    path('urts/ficha/especie-vegetal/deletar/<int:vegetal_id>/', especie_vegetal_deletar, name='especie_vegetal_deletar'),

    #ESPÉCIE ANIMAL
    path('urts/ficha/especie-animal/<int:animal_id>/dados/', especie_animal_modal, name='especie_animal_modal'),
    path('urts/ficha/especie-animal/salvar/novo/', especie_animal_salvar, name='especie_animal_salvar_novo'),
    path('urts/ficha/especie-animal/salvar/<int:animal_id>/', especie_animal_salvar, name='especie_animal_salvar'),
    path('urts/ficha/especie-animal/deletar/<int:animal_id>/', especie_animal_deletar, name='especie_animal_deletar'),

    #TECNICOS DA URT
    path('urts/ficha/tecnico/<int:tecnico_id>/dados/', tecnico_modal, name='tecnico_modal'),
    path('urts/ficha/tecnico/salvar/novo/', tecnico_salvar, name='tecnico_salvar_novo'),
    path('urts/ficha/tecnico/salvar/<int:tecnico_id>/', tecnico_salvar, name='tecnico_salvar'),
    path('urts/ficha/tecnico/deletar/<int:tecnico_id>/', tecnico_deletar, name='tecnico_deletar'),

    #CICLOS DA URT
    path('urts/ficha/ciclo/', listagem_ciclos_urt, name='listagem_ciclos_urt'),
    path('urts/ficha/ciclo/ficha/', ciclo_urt_ficha, name='ciclo_urt_ficha'),


    #RELATÓRIOS
    path('urts/relatorio/ficha-urt/<int:urt_id>/', urt_relatorio_ficha, name='urt_relatorio_ficha'),

]

setup/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.main.urls')),
    path('', include('apps.usuarios.urls')),
    path('', include('apps.urts.urls')),
    path('select2/', include('django_select2.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/urts/models.py
from django.db import models
from apps.usuarios.models import Usuarios
from datetime import timedelta
from django.utils import timezone
from setup.choices import (LISTA_UFS_SIGLAS, LISTA_TEXTURA_SOLO, LISTA_MESES, 
                           ESPECIES_ANIMAIS, ESPECIES_VEGETAIS, LOCAL_PREPARO_AMOSTRAS,
                           STATUS_CONTRATOS_TECNICOS, FORMACAO_TECNICA, PERIODO_CLIMATICO,
                           CICLO_FASES, CICLO_TIPO_ATIVIDADE, CICLO_STATUS_ATIVIDADE,
                           TIPO_ESPECIE, CICLO_STATUS, FASE_PROJETO_FORRAGEIRAS
                        )

#URT
class URTs(models.Model):
    #relacionamento
    usuario_registro = models.ForeignKey(Usuarios, on_delete=models.DO_NOTHING, related_name='usuario_urt_registro')
    usuario_atualizacao = models.ForeignKey(Usuarios, on_delete=models.DO_NOTHING, related_name='usuario_urt_edicao')
    
    #log
    registro_data = models.DateTimeField(auto_now_add=True)
    ult_atual_data = models.DateTimeField(auto_now=True)
    log_n_edicoes = models.IntegerField(default=1)

    #propriedade
    nome_propriedade = models.CharField(max_length=120, null=True, blank=True)
    proprietario_nome = models.CharField(max_length=120, null=True, blank=True)
    proprietario_telefone = models.CharField(max_length=15, null=True, blank=True)
    proprietario_celular = models.CharField(max_length=15, null=True, blank=True)
    proprietario_email = models.EmailField(max_length=80, null=True, blank=True)
    
    #localizacao
    uf = models.CharField(max_length=2, choices=LISTA_UFS_SIGLAS, null=False, blank=False)
    municipio = models.CharField(max_length=120, null=False, blank=False)
    endereco = models.TextField(null=True, blank=True)
    latlong = models.CharField(max_length=60, null=True, blank=True)
    pluscode = models.CharField(max_length=60, null=True, blank=True)

    #caracteristicas gerais
    area_experimento = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    textura_solo = models.CharField(max_length=30, choices=LISTA_TEXTURA_SOLO, null=True, blank=True)
    local_preparo_amostras = models.CharField(max_length=120, choices=LOCAL_PREPARO_AMOSTRAS, null=True, blank=True)

    #clima
    precipitacao_anual = models.IntegerField(null=True, blank=True)
    periodo_chuva_inicio = models.IntegerField(choices=LISTA_MESES, null=True, blank=True)
    periodo_chuva_fim = models.IntegerField(choices=LISTA_MESES, null=True, blank=True)
    periodo_seca_inicio = models.IntegerField(choices=LISTA_MESES, null=True, blank=True)
    periodo_seca_fim = models.IntegerField(choices=LISTA_MESES, null=True, blank=True)
    
    #dados da federacao
    federacao_presidente = models.CharField(max_length=120, null=True, blank=True)
    federacao_telefone = models.CharField(max_length=15, null=True, blank=True)
    federacao_email = models.EmailField(max_length=80, null=True, blank=True)

    #dados senar
    senar_superintendente = models.CharField(max_length=120, null=True, blank=True)
    senar_telefone = models.CharField(max_length=15, null=True, blank=True)
    senar_email = models.EmailField(max_length=80, null=True, blank=True)

    #supervisor URT
    supervisor_nome = models.CharField(max_length=120, null=True, blank=True)
    supervisor_telefone = models.CharField(max_length=15, null=True, blank=True)
    supervisor_email = models.EmailField(max_length=80, null=True, blank=True)

    #observacoes
    observacoes_gerais = models.TextField(null=True, blank=True, default='Sem observações.')

    #delete (del)
    del_status = models.BooleanField(default=False)
    del_data = models.DateTimeField(null=True, blank=True)
    del_usuario = models.ForeignKey(Usuarios, on_delete=models.DO_NOTHING, null=True, blank=True, related_name='usuario_urt_deletado')

    def save(self, *args, **kwargs):
        user = kwargs.pop('current_user', None)
        if self.id:
            self.log_n_edicoes += 1
            if user:
                self.usuario_atualizacao = user
        else:
            if user:
                self.usuario_registro = user
                self.usuario_atualizacao = user
        super(URTs, self).save(*args, **kwargs)


    def soft_delete(self, user):
        self.del_status = True
        self.del_data = timezone.now()
        self.del_usuario = user
        self.save()

    def tecnico_atual(self):
        # Filtra os técnicos associados a esta URT com status 'em_execucao'
        tecnicos = TecnicoURT.objects.filter(urt=self, status_contrato='em_execucao', del_status=False)

        # Retorna os dados do primeiro técnico encontrado ou None se nenhum for encontrado
        if tecnicos.exists():
            tecnico = tecnicos.first()
            dados_tecnico = {
                'tecnico': tecnico.tecnico,
                'formacao': tecnico.get_formacao_tecnica_display,
                'celular': tecnico.celular,
                'email': tecnico.email,
                'status_contrato': tecnico.status_contrato,
                'data_inicio': tecnico.data_inicio,
                'data_fim': tecnico.data_fim
            }
            return dados_tecnico
        else:
            return None

    def especies_vegetais_urt(self):
        especies_vegetais = URTespecieVegetal.objects.filter(urt=self, del_status=False)
        lista_especies = [especie.especies_variedades() for especie in especies_vegetais]
        return ';<br> '.join(lista_especies)
    
    def especies_animais_urt(self):
        especies_animais = URTespecieAnimal.objects.filter(urt=self, del_status=False)
        lista_especies = [especie.especies_racas() for especie in especies_animais]
        return ';<br> '.join(lista_especies)

    def __str__(self):
        return f"URT: {self.municipio}-{self.uf}"


#ESPÉCIES VEGETAIS E ANIMAIS
class URTespecieVegetal(models.Model):
    #relacionamento
    usuario_registro = models.ForeignKey(Usuarios, on_delete=models.DO_NOTHING, related_name='usuario_urt_vegetal_registro')
    usuario_atualizacao = models.ForeignKey(Usuarios, on_delete=models.DO_NOTHING, related_name='usuario_urt_vegetal_edicao')
    
    #log
    registro_data = models.DateTimeField(auto_now_add=True)
    ult_atual_data = models.DateTimeField(auto_now=True)
    log_n_edicoes = models.IntegerField(default=1)

    #dados da especie vegetal
    especie_vegetal = models.CharField(max_length=120, choices=ESPECIES_VEGETAIS, null=True, blank=True)
    variedades = models.TextField(null=True, blank=True)
    area_utilizada = models.FloatField(null=True, blank=True, default=0)
    producao_silagem = models.BooleanField(null=True, blank=True)
    
    #relacionamento
    urt = models.ForeignKey(URTs, on_delete=models.DO_NOTHING, related_name='urt_especie_vegetal')

    #observacoes
    observacoes_gerais = models.TextField(null=True, blank=True, default='Sem observações.')

    #delete (del)
    del_status = models.BooleanField(default=False)
    del_data = models.DateTimeField(null=True, blank=True)
    del_usuario = models.ForeignKey(Usuarios, on_delete=models.DO_NOTHING, null=True, blank=True, related_name='usuario_urt_vegetal_deletado')

    def save(self, *args, **kwargs):
        user = kwargs.pop('current_user', None)

        # Se o objeto já tem um ID, então ele já existe no banco de dados
        if self.id:
            self.log_n_edicoes += 1
            if user:
                self.usuario_atualizacao = user
        else:
            if user:
                self.usuario_registro = user
                self.usuario_atualizacao = user
        super(URTespecieVegetal, self).save(*args, **kwargs)

    def soft_delete(self, user):
        self.del_status = True
        self.del_data = timezone.now()
        self.del_usuario = user
        self.save()

    def especies_variedades(self):
        especie_display = self.get_especie_vegetal_display()
        return f"{especie_display}: {self.variedades}"

    def __str__(self):
        return f"URT: {self.urt.municipio}-{self.urt.uf} - Espécies Vegetais: {self.especie_vegetal}"

class URTespecieAnimal(models.Model):
    #relacionamento
    usuario_registro = models.ForeignKey(Usuarios, on_delete=models.DO_NOTHING, related_name='usuario_urt_animal_registro')
    usuario_atualizacao = models.ForeignKey(Usuarios, on_delete=models.DO_NOTHING, related_name='usuario_urt_animal_edicao')
    
    #log
    registro_data = models.DateTimeField(auto_now_add=True)
    ult_atual_data = models.DateTimeField(auto_now=True)
    log_n_edicoes = models.IntegerField(default=1)

    #dados da especie animal
    especie_animal = models.CharField(max_length=120, choices=ESPECIES_ANIMAIS, null=True, blank=True)
    racas = models.TextField(null=True, blank=True)
    area_utilizada = models.FloatField(null=True, blank=True, default=0)
    
    #relacionamento
    urt = models.ForeignKey(URTs, on_delete=models.DO_NOTHING, related_name='urt_especie_animal')

    #observacoes
    observacoes_gerais = models.TextField(null=True, blank=True, default='Sem observações.')

    #delete (del)
    del_status = models.BooleanField(default=False)
    del_data = models.DateTimeField(null=True, blank=True)
    del_usuario = models.ForeignKey(Usuarios, on_delete=models.DO_NOTHING, null=True, blank=True, related_name='usuario_urt_animal_deletado')

    def save(self, *args, **kwargs):
        user = kwargs.pop('current_user', None)

        # Se o objeto já tem um ID, então ele já existe no banco de dados
        if self.id:
            self.log_n_edicoes += 1
            if user:
                self.usuario_atualizacao = user
        else:
            if user:
                self.usuario_registro = user
                self.usuario_atualizacao = user
        super(URTespecieAnimal, self).save(*args, **kwargs)

    def soft_delete(self, user):
        self.del_status = True
        self.del_data = timezone.now()
        self.del_usuario = user
        self.save()
    
    def especies_racas(self):

templates/urts/urt_ficha_relatorio.html
{% load static %}
{% load humanize %}
<!DOCTYPE html>
<html>
<head>
    <link rel="stylesheet" href="{% static '\styles\_tabelas.css' %}">
    <link rel="stylesheet" href="{% static '/styles/relatorio_urt_ficha.css' %}">
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@400;700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
    <title>URT {{ urt.municipio }}-{{ urt.uf }}</title>
</head>
<body>
    <div class="header">
        <div class="logo-projeto">
            <img src="{% static '/assets/logo/forrageiras.png' %}" alt="Logo SisDAF" class="top-logo">
        </div>
        <div class="titulo-relatorio">
            Ficha da URT <b style="text-transform: uppercase;">{{ urt.municipio }}-{{ urt.uf }}</b>
        </div>
        <div class="responsavel-exportacao">
            {{ usuario }} - {{ data_hora }}
        </div>
    </div>

    <div class="content">

        <!-- Log -->
        <div class="horizontal-section log">
            <div class="section">
                <div class="section-titulo">
                    Log
                </div>
                <div class="grid">
                    <div class="box">
                        <div class="box-titulo">ID</div>
                        <div class="box-conteudo">{{ urt.id }}</div>
                    </div>
                    <div class="box">
                        <div class="box-titulo">Responsável Registro</div>
                        <div class="box-conteudo">{{ urt.usuario_registro.primeiro_ultimo_nome }}</div>
                    </div>
                    <div class="box">
                        <div class="box-titulo">Data Registro</div>
                        <div class="box-conteudo">{{ urt.registro_data|date:"d/m/Y H:i:s" }}</div>
                    </div>
                    <div class="box">
                        <div class="box-titulo">Responsável Últ. Atualização</div>
                        <div class="box-conteudo">{{ urt.usuario_atualizacao.primeiro_ultimo_nome }}</div>
                    </div>
                    <div class="box">
                        <div class="box-titulo">Última Atualização</div>
                        <div class="box-conteudo">{{ urt.ult_atual_data|date:"d/m/Y H:i:s" }}</div>
                    </div>
                    <div class="box">
                        <div class="box-titulo">Nº Edições</div>
                        <div class="box-conteudo">{{ urt.log_n_edicoes }}</div>
                    </div>
                </div>
            </div>
        </div>

        <!-- Identificação da URT -->
        <div class="horizontal-section log">
            <div class="section">
                <div class="section-titulo">
                    Identificação da URT
                </div>

                <!-- UF, Município, Nome da Propriedade, Proprietário -->
                <div class="grid">
                    <div class="box">
                        <div class="box-titulo">UF</div>
                        <div class="box-conteudo">{{ urt.get_uf_display }}</div>
                    </div>                    
                    <div class="box">
                        <div class="box-titulo">Município</div>
                        <div class="box-conteudo">{{ urt.municipio }}</div>
                    </div>
                    <div class="box">
                        <div class="box-titulo full-width">Nome da Propriedade</div>
                        <div class="box-conteudo">{{ urt.nome_propriedade }}</div>
                    </div>
                    <div class="box">
                        <div class="box-titulo">Proprietário</div>
                        <div class="box-conteudo">{{ urt.proprietario_nome }}</div>
                    </div>
                    <div class="box">
                        <div class="box-titulo">Celular</div>
                        <div class="box-conteudo">{{ urt.proprietario_celular }}</div>
                    </div>
                    <div class="box">
                        <div class="box-titulo">Email</div>
                        <div class="box-conteudo">{{ urt.proprietario_email }}</div>
                    </div>
                    
                </div>

                <!-- Endereço -->
                <div class="grid">
                    <div class="box full-width">
                        <div class="box-titulo">Endereço</div>
                        <div class="box-conteudo">{{ urt.endereco }}</div>
                    </div>
                    <div class="box">
                        <div class="box-titulo">LatLong</div>
                        <div class="box-conteudo">{{ urt.latlong }}</div>
                    </div>
                    <div class="box">
                        <div class="box-titulo">PlusCode</div>
                        <div class="box-conteudo">{{ urt.pluscode }}</div>
                    </div>
                </div>

            </div>
        </div>

        <!-- Técnico Responsável -->
        <div class="horizontal-section log">
            <div class="section">
                <div class="section-titulo">
                    Técnico Responsável
                </div>

                <!-- Dados do Técnico -->
                <div class="grid">
                    <div class="box full-width">
                        <div class="box-titulo">Técnico</div>
                        <div class="box-conteudo">{{ urt.tecnico_atual.tecnico }}</div>
                    </div>
                    <div class="box">
                        <div class="box-titulo">Formação Técnica</div>
                        <div class="box-conteudo">{{ urt.tecnico_atual.formacao }}</div>
                    </div>                 
                    <div class="box">
                        <div class="box-titulo">Celular</div>
                        <div class="box-conteudo">{{ urt.tecnico_atual.celular }}</div>
                    </div>
                    <div class="box">
                        <div class="box-titulo">Email</div>
                        <div class="box-conteudo">{{ urt.tecnico_atual.email }}</div>
                    </div>
                    <div class="box">
                        <div class="box-titulo">Data Início</div>
                        <div class="box-conteudo">{{ urt.tecnico_atual.data_inicio|date:'d/m/Y' }}</div>
                    </div>
                    
                </div>

            </div>
        </div>

        <!-- Dados do Experimento -->
        <div class="horizontal-section log">
            <div class="section">
                <div class="section-titulo">
                    Dados do Experimento
                </div>

                <!-- UF, Município, Nome da Propriedade, Proprietário -->
                <div class="grid">
                    <div class="box">
                        <div class="box-titulo">Área Total (ha)</div>
                        <div class="box-conteudo">{{ urt.area_experimento }}</div>
                    </div>                    
                    <div class="box">
                        <div class="box-titulo">Textura do Solo</div>
                        <div class="box-conteudo">{{ urt.get_textura_solo_display }}</div>
                    </div>
                    <div class="box">
                        <div class="box-titulo full-width">Local Preparo Amostras</div>
                        <div class="box-conteudo">{{ urt.get_local_preparo_amostras_display }}</div>
                    </div>

                    <div class="box">
                        <div class="box-titulo full-width">Precipitação Anual (mm)</div>
                        <div class="box-conteudo">{{ urt.precipitacao_anual }}</div>
                    </div>
                    <div class="box">
                        <div class="box-titulo full-width">Período Chuvoso</div>
                        <div class="box-conteudo">{{ urt.get_periodo_chuva_inicio_display }} a {{ urt.get_periodo_chuva_fim_display }}</div>
                    </div>
                    <div class="box">
                        <div class="box-titulo full-width">Período de Seca</div>
                        <div class="box-conteudo">{{ urt.get_periodo_seca_inicio_display }} a {{ urt.get_periodo_seca_fim_display }}</div>
                    </div>
                </div>

                <!-- Endereço -->
                <div class="grid">
                    <div class="box full-width">
                        <div class="box-titulo">Endereço</div>
                        <div class="box-conteudo">{{ urt.endereco }}</div>
                    </div>
                    <div class="box">
                        <div class="box-titulo">LatLong</div>
                        <div class="box-conteudo">{{ urt.latlong }}</div>
                    </div>
                    <div class="box">
                        <div class="box-titulo">PlusCode</div>
                        <div class="box-conteudo">{{ urt.pluscode }}</div>
                    </div>
                </div>
                
            </div>
        </div>

        <!-- Espécies Vegetais e Animais -->
        <div class="horizontal-section log">
            <div class="section">
                <div class="section-titulo">
                    Espécies Animais e Vegetais
                </div>
                
                <span style="font-size: 10px; font-weight: bold; text-align: left; padding-left: 10px;">Espécies Vegetais</span>
                <div class="grid" style="justify-content:center !important;" >
                    
                    <table class="tabela-relatorio" style="font-size: 10px; ">
                        <thead>
                            <tr>
                                <th class="col-texto4" style="text-align: left;">ID</th>
                                <th class="col-texto6">Espécie</th>
                                <th class="col-texto20">Raças</th>
                                <th class="col-texto4"></th>
                                <th class="col-valor5">Área (ha)</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for item in tab_especies_animais %}
                            <tr data-id="{{ item.id }}">
                                <td class="col-texto4">{{ item.id }}</td>
                                <td class="col-texto6">{{ item.get_especie_animal_display }}</td>
                                <td class="col-texto20">{{ item.racas }}</td>
                                <td class="col-texto4"></td>
                                <td class="col-valor5">{{ item.area_utilizada }}</td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table> 
                </div>

                <!-- Espécies Vegetais -->
                <span style="font-size: 10px; font-weight: bold; text-align: left; padding-left: 10px;">Espécies Vegetais</span>
                <div class="grid" style="justify-content:center !important;" >
                    
                    <table class="tabela-relatorio" style="font-size: 10px; ">
                        <thead>
                            <tr>
                                <th class="col-texto4" style="text-align: left;">ID</th>
                                <th class="col-texto6">Espécie</th>
                                <th class="col-texto20">Variedades</th>
                                <th class="col-texto4">Silagem</th>
                                <th class="col-valor5">Área (ha)</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for item in tab_especies_vegetais %}
                            <tr data-id="{{ item.id }}">
                                <td class="col-texto4">{{ item.id }}</td>
                                <td class="col-texto6">{{ item.get_especie_vegetal_display }}</td>
                                <td class="col-texto12">{{ item.variedades }}</td>
                                <td class="col-texto4">
                                    {% if item.producao_silagem %}
                                        Sim
                                    {% else %}
                                        Não
                                    {% endif %}
                                </td>
                                <td class="col-valor5">{{ item.area_utilizada }}</td>
                                
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table> 
                </div>

            </div>
        </div>

        <!-- Observações gerais -->
        <div class="horizontal-section log">
            <div class="section full-width">
                <div class="section-titulo">
                    Observações Gerais
                </div>
                <div class="grid">
                    <div class="box-observacoes">
                        <div class="box-conteudo">{{ urt.observacoes_gerais }}</div>
                    </div>
                    
                    
                </div>

            </div>
        </div>

    </div>

    <!-- <div class="footer">
        <div class="relatorio-log">
            {{ usuario }} - {{ data_hora }}
        </div>
        
        <div class="footer-pagina">
            Página <b>1</b> de <b>1</b>
        </div>
    </div> -->
</body>


</html>

templates/urts/urts.html
{% extends 'main/base_main.html' %}
{% load static %}
{% block extra_head %}
    <link rel="stylesheet" href="{% static 'styles/_tabelas.css' %}">
    <link rel="stylesheet" href="{% static '\styles\urt.css' %}">
    
{% endblock %}
{% block content %}    
    
    <!-- Caminho da Área de Trabalho -->
    <div class="breadcrumb2">
        <i class="fa-solid fa-seedling"></i></i>&nbsp;URTs
    </div>

    <!-- Barra Superior -->
    <div class="barra-superior">
        <!-- Abas -->
        <div class="tabs">
            <button class="tab-button active" id="abaURTs">Lista de URTs</button>
        </div>
    </div>

    <!-- <div class="horizontal-sections">
        
        <div class="section numbers">
            <div class="filter-title">
                Total de URTs
            </div>
            <div id="numeroProjetos" class="total-geral">{{ tab_urts.count }}</div>
        </div>
        
        <div class="section filter">
            <div class="filter-title">Filtros
                Filtros
            </div>
            
            <div class="form-floating">
                {{ form_filtro.regional }}
                <label>{{ form_filtro.regional.label }}</label>
            </div>

            <div class="form-floating">
                {{ form_filtro.status }}
                <label>{{ form_filtro.status.label }}</label>
            </div>

            <div class="form-floating">
                {{ form_filtro.subprograma }}
                <label>{{ form_filtro.subprograma.label }}</label>
            </div>

             <div class="form-floating">
                {{ form_filtro.data_inicio }}
                <label>{{ form_filtro.data_inicio.label }}</label>
            </div>
            <div class="form-floating">
                {{ form_filtro.data_fim }}
                <label>{{ form_filtro.data_fim.label }}</label>
            </div>               

            <div class="form-floating full-width">
                {{ form_filtro.nome_plano_trabalho }}
                <label>{{ form_filtro.nome_plano_trabalho.label }}</label>
            </div>   
    
            <button class="custom-btn limpar-filtro-fornecedores">
                <i class="fa fa-times" style="font-size: 1.5vw" title="Limpar filtros" id="filtro_limpar"></i>
                <span style="font-size: 10px;">Limpar Filtros</span>
            </button>
        </div>

        <div class="section funcionalidades">
            <div style="font-size: 12px; font-weight: bold;">
                Funcionalidades
            </div>
            <div class="btn-container">
                <button class="custom-btn" id="exportarBtn">
                    <div class="icon-container">
                        <i class="fa fa-download" style="font-size: 1.5vw"></i>
                        <span>Exportar</span>
                    </div>                    
                </button>
                
            </div>   
        </div>
        
    </div> -->

    <div class="section-tabela">
        <table class="table table-striped table-hover fixed-size-table" style="font-size: 14px;" id="tabURTs">
            <thead>
                <tr>
                    <th class="col-texto4">ID</th>
                    <th class="col-texto4">UF</th>
                    <th class="col-texto12">Município</th>
                    <th class="col-texto8">Precip. Anual</th>
                    <th class="col-texto6">Chuvas/In.</th>
                    <th class="col-texto6">Chuvas/Fim</th>
                    <th class="col-texto8">Técnico Resp.</th>
                    <th class="col-texto8">Celular</th>
                    <th class="col-texto15">Espécies Vegetais</th>
                    <th class="col-texto15">Espécies Animais</th>
                </tr>
            </thead>
            <tbody>
                {% for item in tab_urts %}
                <tr data-id="{{ item.id }}">
                    <td class="col-texto4">{{ item.id }}</td>
                    <td class="col-texto4">{{ item.get_uf_display }}</td>
                    <td class="col-texto12">{{ item.municipio }}</td>
                    <td class="col-texto8">{{ item.precipitacao_anual|default:'NI' }}</td>
                    <td class="col-texto6">{{ item.get_periodo_chuva_inicio_display|default:'NI' }}</td>
                    <td class="col-texto6">{{ item.get_periodo_chuva_fim_display|default:'NI' }}</td>
                    <td class="col-texto8">{{ item.tecnico_atual.tecnico }}</td>
                    <td class="col-texto8">{{ item.tecnico_atual.celular }}</td>
                    <td class="col-texto15">{{ item.especies_vegetais_urt|safe }}</td>
                    <td class="col-texto15">{{ item.especies_animais_urt|safe }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>  
    </div>
    

    </div>
    
    <script src="{% static 'js/urts.js' %}"></script>


{% endblock %}